[package]
name = "taconite"
version = "0.1.0"
edition = "2021"
authors = ["TeaSpillStudios <TeaSpillStudios@proton.me>"]
license = "MIT"
homepage = "https://TeaSpillStudios.vercel.app/projects/taconite"
repository = "https://github.com/TeaSpillStudios/Taconite"
description = "A simple game engine wrote in rust for simplicity, speed and memory safety."

[dependencies]
glow = "0.12.1"
glutin = "0.28"
log = "0.4.17"
num_cpus = "1.15.0"

[dev-dependencies]
pretty_env_logger = "0.4.0"

[lib]
name = "taconite"
path = "src/lib.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
