[package]
name = "taconite"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.12.3"
ecs_rust = "0.0.4"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}

[lib]
name = "taconite"
path = "src/lib.rs"

[dev-dependencies]
beryllium = "0.9.0"
