[package]
name = "taconite"
version = "0.1.0"
edition = "2021"
authors = [ "TeaSpillStudios <TeaSpillStudios@proton.me>" ]
license = "MIT"
homepage = "https://TeaSpillStudios.vercel.app/projects/taconite"
repository = "https://github.com/TeaSpillStudios/Taconite"
description = "A simple game engine wrote in rust for simplicity, speed and memory safety."

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
sdl2 = { version = "0.35.2", features = [ "image" ] }

[lib]
name = "taconite"
path = "src/lib.rs"

[profile.release]
lto = true
codegen-units = 1

[dev-dependencies]
env_logger = "0.10.0"
